### ISSUE TITLE
[karma]: TypeError: Cannot read property '282082' of undefined

### ISSUE THREAD

**Issue by imran-khan8** [karma-runner/karma-jasmine#173]
I am getting following error, when I run unit tests using Karma.

start /wait /b karma start karma.conf.js --single-run=false --debug

```
>06 04 2017 14:42:55.804:WARN [karma]: No captured browser, open http://localhost:9876/
06 04 2017 14:42:55.822:INFO [karma]: Karma v1.6.0 server started at http://0.0.0.0:9876/
06 04 2017 14:42:55.823:INFO [launcher]: Launching browser IE with unlimited concurrency
06 04 2017 14:42:55.846:INFO [launcher]: Starting browser IE
06 04 2017 14:42:56.283:ERROR [launcher]: Cannot start IE

06 04 2017 14:42:56.291:INFO [launcher]: Trying to start IE again (1/2).
06 04 2017 14:42:56.602:ERROR [launcher]: Cannot start IE

06 04 2017 14:42:56.604:INFO [launcher]: Trying to start IE again (2/2).
06 04 2017 14:42:56.918:ERROR [launcher]: Cannot start IE

06 04 2017 14:42:56.920:ERROR [launcher]: IE failed 2 times (cannot start). Giving up.
06 04 2017 14:42:57.561:INFO [IE 11.0.0 (Windows 7 0.0.0)]: Connected on socket
LTIJrd8SONtDpWMEAAAC with id 282082
06 04 2017 14:43:07.567:WARN [IE 11.0.0 (Windows 7 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
IE 11.0.0 (Windows 7 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.

06 04 2017 14:43:07.570:ERROR [karma]: TypeError: Cannot read property '282082'
of undefined
    at HTMLReporter.onBrowserComplete (\node_modules\karma-htmlfile-reporter\index.js:97:23)
    at Server.<anonymous> (\node_modules\karma\lib\events.js:13:22)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Timeout._onTimeout (\node_modules\karma\lib\browser.js:51:15)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
```
Here is the dependencies in **package.json**

```
"dependencies": {
        "karma": "1.6.0",
        "karma-jasmine": "0.3.6",
        "jasmine-core" : "2.4.1",

        "angular": "1.4.7",
        "angular-mocks": "1.4.7",

        "karma-htmlfile-reporter": "0.2.2",
        "karma-ie-launcher": "0.2.0",
        
        "karma-cli": "1.0.1"

    }
```
**Karma.conf.js**

```

var sourcePreprocessors = 'coverage';
function isDebug(argument) {
    return argument === '--debug';
}
if (process.argv.some(isDebug)) {
    sourcePreprocessors = [];
}

module.exports = function(config) {
  config.set({
	  
	plugins: [
	  'karma-jasmine',
	  'karma-ie-launcher',
	  'karma-htmlfile-reporter'
	],

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine'],

    // list of files / patterns to load in the browser
    files: [
      'node_modules/angular/angular.js',
      'node_modules/angular-mocks/angular-mocks.js',
      'BaseAppTests/*.js'
    ],


    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
        'index.js': sourcePreprocessors,
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress', 'html'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
	// PhantomJS , IE
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['IE'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    // Concurrency level
    // how many browser should be started simultanous
    concurrency: Infinity,
	
	// Karma HTML File Reporter config
    htmlReporter: {
      outputFile: 'unit_test_results.html',
	  // Optional
      pageTitle: 'Unit Tests',
      subPageTitle: 'Results'
	}
  })
}

```

Any help is appreciated.
Thanks

**Comment by maksimr** [comment]
@imran-khan8 the problem in **karma-htmlfile-reporter**

> 06 04 2017 14:43:07.570:ERROR [karma]: TypeError: Cannot read property '282082'
of undefined
    at HTMLReporter.onBrowserComplete (\node_modules\karma-htmlfile-reporter\index.js:97:23)

Thanks
