### ISSUE TITLE
DOMTestComponentRenderer.insertRootElement when mocking document.querySelectorAll

### ISSUE THREAD

**Issue by argelj289** [karma-runner/karma-jasmine#284]
when I try to use spyOn to document.querySelectorAll, it gives me error like

```
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at DOMTestComponentRenderer.insertRootElement (http://localhost:9876/packages/platform-browser-dynamic/testing/src/dom_test_component_renderer.ts:29:34)
    at TestBedRender3.createComponent (http://localhost:9876/packages/core/testing/src/r3_test_bed.ts:336:27)
    at Function.createComponent (http://localhost:9876/packages/core/testing/src/r3_test_bed.ts:182:33)
    at setup (http://localhost:9876/_karma_webpack_/src/app/components/message-management/message/message.component.spec.ts:838:29)
    at UserContext.apply (http://localhost:9876/_karma_webpack_/src/app/components/message-management/message/message.component.spec.ts:931:65)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:386:30)
    at ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:292:43)
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:385:36)
    at Zone.run (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone.js:143:47)
    at runInTestZone (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:545:38)

```

**Comment by johnjbarton** [comment]
`testing/src/dom_test_component_renderer.ts:29` <-- look there. 

This is not related to karma-jasmine, jasmine, or karma.
